version: "3"

networks:
  network_redis_cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16

services:
  redis-master-a:
    image: redis:latest
    networks:
      network_redis_cluster:
        ipv4_address: 173.18.0.11
    ports:
      - "6381:6381"
      - "16381:16381"
    volumes:
      - ./redis-master-a:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    restart: always
  
  redis-master-b:
    image: redis:latest
    networks:
      network_redis_cluster:
        ipv4_address: 173.18.0.12
    ports:
      - "6382:6382"
      - "16382:16382"
    volumes:
      - ./redis-master-b:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    restart: always
  
  redis-master-c:
    image: redis:latest
    networks:
      network_redis_cluster:
        ipv4_address: 173.18.0.13
    ports:
      - "6383:6383"
      - "16383:16383"
    volumes:
      - ./redis-master-c:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    restart: always
  
  redis-replica-a:
    image: redis:latest
    networks:
      network_redis_cluster:
        ipv4_address: 173.18.0.14
    ports:
      - "6384:6384"
      - "16384:16384"
    volumes:
      - ./redis-replica-a:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    restart: always
  
  redis-replica-b:
    image: redis:latest
    networks:
      network_redis_cluster:
        ipv4_address: 173.18.0.15
    ports:
      - "6385:6385"
      - "16385:16385"
    volumes:
      - ./redis-replica-b:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    restart: always
  
  redis-replica-c:
    image: redis:latest
    networks:
      network_redis_cluster:
        ipv4_address: 173.18.0.16
    ports:
      - "6386:6386"
      - "16386:16386"
    volumes:
      - ./redis-replica-c:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    restart: always
  
  redis-cluster-creator:
    image: redis:latest
    networks:
      network_redis_cluster:
        ipv4_address: 173.18.0.17
    ports:
      - "6387:6387"
      - "16387:16387"
    tty: true
    command: redis-cli -a password --cluster create 173.18.0.11:6381 173.18.0.12:6382 173.18.0.13:6383 173.18.0.14:6384 173.18.0.15:6385 173.18.0.16:6386 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-master-a
      - redis-master-b
      - redis-master-c
      - redis-replica-a
      - redis-replica-b
      - redis-replica-c